# 5. customers_dashboard.parquet

- 크기: 1,362,281행 × 8열
<!-- - 컬럼 명세는 [README.md](README.md#43-articlescsv) 참고 -->

In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path('../data')

## 데이터 불러오기

In [2]:
customers_dashboard = pd.read_parquet(DATA_DIR / 'customers_dashboard.parquet')

## 기본 정보

In [4]:
customers_dashboard.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1362281 entries, 0 to 1362280
Data columns (total 8 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   customer_id               1362281 non-null  object
 1   age                       1362281 non-null  int64
 2   club_member_status        1356227 non-null  object
 3   fashion_news_frequency    1346281 non-null  object
 4   last_purchase             1362281 non-null  datetime64[us]
 5   purchase_count            1362281 non-null  int64
 6   total_spent               1362281 non-null  float64
 7   days_since_last_purchase  1362281 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(3), object(3)
memory usage: 83.1+ MB

In [5]:
customers_dashboard.describe()

,age,last_purchase,purchase_count,total_spent,days_since_last_purchase
count,1.362281e+06,1362281,1.362281e+06,1.362281e+06,1.362281e+06
mean,3.596334e+01,2020-01-30 20:26:15.037161,2.333463e+01,6.493858e-01,2.351484e+02
min,-1.000000e+00,2018-09-20 00:00:00,1.000000e+00,7.627119e-04,0.000000e+00
25%,2.400000e+01,2019-08-21 00:00:00,3.000000e+00,8.806780e-02,4.800000e+01
50%,3.100000e+01,2020-04-24 00:00:00,9.000000e+00,2.455932e-01,1.510000e+02
75%,4.900000e+01,2020-08-05 00:00:00,2.700000e+01,7.011864e-01,3.980000e+02
max,9.900000e+01,2020-09-22 00:00:00,1.895000e+03,5.767641e+01,7.330000e+02
std,1.477515e+01,NaN,3.924225e+01,1.197582e+00,2.211188e+02

In [6]:
customers_dashboard.head()

,customer_id,age,club_member_status,fashion_news_frequency,last_purchase,purchase_count,total_spent,days_since_last_purchase
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,49,ACTIVE,NONE,2020-09-05,21,0.648983,17
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,25,ACTIVE,NONE,2020-07-08,86,2.601932,76
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,24,ACTIVE,NONE,2020-09-15,18,0.704780,7
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,54,ACTIVE,NONE,2019-06-09,2,0.060983,471
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,52,ACTIVE,Regularly,2020-08-12,13,0.469695,41