In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_parquet('../data/customers_dashboard.parquet')
print(df.head(5))

                                         customer_id  age club_member_status  \
0  00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...   49             ACTIVE
1  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...   25             ACTIVE
2  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   24             ACTIVE
3  00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...   54             ACTIVE
4  00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...   52             ACTIVE

  fashion_news_frequency last_purchase  purchase_count  total_spent  \
0                   NONE    2020-09-05              21     0.648983
1                   NONE    2020-07-08              86     2.601932
2                   NONE    2020-09-15              18     0.704780
3                   NONE    2019-06-09               2     0.060983
4              Regularly    2020-08-12              13     0.469695

   days_since_last_purchase
0                        17
1                        76
2                         7
3                       471
4                        41

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1362281 entries, 0 to 1362280
Data columns (total 8 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   customer_id               1362281 non-null  object
 1   age                       1362281 non-null  int64
 2   club_member_status        1356227 non-null  object
 3   fashion_news_frequency    1346281 non-null  object
 4   last_purchase             1362281 non-null  datetime64[us]
 5   purchase_count            1362281 non-null  int64
 6   total_spent               1362281 non-null  float64
 7   days_since_last_purchase  1362281 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(3), object(3)
memory usage: 83.1+ MB

,age,last_purchase,purchase_count,total_spent,days_since_last_purchase
count,1.362281e+06,1362281,1.362281e+06,1.362281e+06,1.362281e+06
mean,3.596334e+01,2020-01-30 20:26:15.037161,2.333463e+01,6.493858e-01,2.351484e+02
min,-1.000000e+00,2018-09-20 00:00:00,1.000000e+00,7.627119e-04,0.000000e+00
25%,2.400000e+01,2019-08-21 00:00:00,3.000000e+00,8.806780e-02,4.800000e+01
50%,3.100000e+01,2020-04-24 00:00:00,9.000000e+00,2.455932e-01,1.510000e+02
75%,4.900000e+01,2020-08-05 00:00:00,2.700000e+01,7.011864e-01,3.980000e+02
max,9.900000e+01,2020-09-22 00:00:00,1.895000e+03,5.767641e+01,7.330000e+02
std,1.477515e+01,NaN,3.924225e+01,1.197582e+00,2.211188e+02

In [5]:
df['club_member_status'].unique()

array(['ACTIVE', None, 'PRE-CREATE', 'LEFT CLUB'], dtype=object)

In [23]:
df[df['club_member_status'].isna() & df['fashion_news_frequency']=='Monthly']

Empty DataFrame
Columns: [customer_id, age, club_member_status, fashion_news_frequency, last_purchase, purchase_count, total_spent, days_since_last_purchase]
Index: []

In [ ]:
df[(df['fashion_news_frequency'] == 'Monthly') & (df['club_member_status'].isna())]

,customer_id,age,club_member_status,fashion_news_frequency,last_purchase,purchase_count,total_spent,days_since_last_purchase
277771,3434af0aef74ccaad677a777ddebc49ab69575f6db0a8f...,43,None,Monthly,2018-10-06,5,0.096525,717
343304,40a5b175c7de5c68a23d3cf967e4b4236e5462a6c5b714...,56,None,Monthly,2018-10-11,1,0.101678,712
356359,431db2b0652cfcc255f0312060442ebd46e6955e03c8cf...,43,None,Monthly,2018-09-29,1,0.067780,724
371639,45fec77a87ca372f03b944394b4560580a3bd806a7aa30...,56,None,Monthly,2020-03-29,7,0.304966,177
772407,9139c57e9331dcc97b3d94c1b2eb040152d67f85b74cf7...,27,None,Monthly,2018-10-15,1,0.059305,708

In [22]:
df['fashion_news_frequency'].unique()

array(['NONE', 'Regularly', None, 'Monthly'], dtype=object)

In [21]:
df[df['fashion_news_frequency'].isna()]

,customer_id,age,club_member_status,fashion_news_frequency,last_purchase,purchase_count,total_spent,days_since_last_purchase
5,000064249685c11552da43ef22a5030f35a147f723d5b0...,-1,None,None,2019-10-02,3,0.101644,356
37,0001bc8e81a72aaf228a103a85d2ac530c09defffbc6ab...,60,ACTIVE,None,2019-11-29,1,0.024390,298
196,0008383d133df1285f2f3d28ef5f50916630069d3a5c7f...,25,ACTIVE,None,2018-12-23,4,0.129085,639
367,0011de63f72ba2f8802076bfd5659485012feb52cd0f49...,30,ACTIVE,None,2019-09-17,3,0.060966,371
396,0012d74ac44959de7ae07dc0fda7e82afff92189196522...,23,ACTIVE,None,2019-10-05,9,0.259186,353
...,...,...,...,...,...,...,...,...
1361981,fff15f528e303627d0dc8b0e9a69fd878a05085b42e72a...,32,PRE-CREATE,None,2018-12-02,11,0.403203,660
1362009,fff2e1f1cd77950a5116764cb5fe856d9a4b80fc17a1a1...,28,ACTIVE,None,2019-10-26,1,0.050831,332
1362014,fff2f4f6d84297f48bed3ad3b1b37574536f1d41afbee4...,21,ACTIVE,None,2019-10-15,2,0.101661,343
1362091,fff67693cb122cc9a939988a5e2194c044e0881b3f1d5f...,33,ACTIVE,None,2019-08-27,2,0.050305,392
1362132,fff8798d2d4c947004bb562d7959954fcd58bc658a6e24...,22,ACTIVE,None,2019-09-25,3,0.076220,363

In [35]:
df.iloc[371639]['customer_id']

'45fec77a87ca372f03b944394b4560580a3bd806a7aa30c6418c909ea3acf98e'

In [36]:
for col in ["days_since_last_purchase", "purchase_count", "total_spent"]:
    print(col, "고유값 비율:", df[col].nunique() / len(df))

days_since_last_purchase 고유값 비율: 0.0005388022001334527
purchase_count 고유값 비율: 0.000548345018391947
total_spent 고유값 비율: 0.36865888902509836