In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_parquet('../data/customers_dashboard.parquet')
print(df.head(5))

                                         customer_id  age club_member_status  \
0  00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...   49             ACTIVE
1  0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...   25             ACTIVE
2  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   24             ACTIVE
3  00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...   54             ACTIVE
4  00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...   52             ACTIVE

  fashion_news_frequency last_purchase  purchase_count  total_spent  \
0                   NONE    2020-09-05              21     0.648983
1                   NONE    2020-07-08              86     2.601932
2                   NONE    2020-09-15              18     0.704780
3                   NONE    2019-06-09               2     0.060983
4              Regularly    2020-08-12              13     0.469695

   days_since_last_purchase
0                        17
1                        76
2                         7
3                       471
4                        41

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1362281 entries, 0 to 1362280
Data columns (total 8 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   customer_id               1362281 non-null  str
 1   age                       1362281 non-null  int64
 2   club_member_status        1356227 non-null  str
 3   fashion_news_frequency    1346281 non-null  str
 4   last_purchase             1362281 non-null  datetime64[us]
 5   purchase_count            1362281 non-null  int64
 6   total_spent               1362281 non-null  float64
 7   days_since_last_purchase  1362281 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 182.1 MB

,age,last_purchase,purchase_count,total_spent,days_since_last_purchase
count,1.362281e+06,1362281,1.362281e+06,1.362281e+06,1.362281e+06
mean,3.596334e+01,2020-01-30 20:26:15.037161,2.333463e+01,6.493858e-01,2.351484e+02
min,-1.000000e+00,2018-09-20 00:00:00,1.000000e+00,7.627119e-04,0.000000e+00
25%,2.400000e+01,2019-08-21 00:00:00,3.000000e+00,8.806780e-02,4.800000e+01
50%,3.100000e+01,2020-04-24 00:00:00,9.000000e+00,2.455932e-01,1.510000e+02
75%,4.900000e+01,2020-08-05 00:00:00,2.700000e+01,7.011864e-01,3.980000e+02
max,9.900000e+01,2020-09-22 00:00:00,1.895000e+03,5.767641e+01,7.330000e+02
std,1.477515e+01,NaN,3.924225e+01,1.197582e+00,2.211188e+02

In [14]:
df.iloc[1002]

customer_id                 002f5809d6d44e2379e65a64728e839e3ac772b96d46bd...
age                                                                        20
club_member_status                                                     ACTIVE
fashion_news_frequency                                              Regularly
last_purchase                                             2020-08-24 00:00:00
purchase_count                                                              3
total_spent                                                           0.08978
days_since_last_purchase                                                   29
Name: 1002, dtype: object

In [9]:
df['club_member_status'].unique()

<ArrowStringArray>
['ACTIVE', nan, 'PRE-CREATE', 'LEFT CLUB']
Length: 4, dtype: str

In [17]:
df['customer_id'][1361466]

'ffd7d77fb2d081a05c849bc78a1a1550ff663d7a483bae58ec31923248965e2a'

In [16]:
df[df['club_member_status'] == 'LEFT CLUB']

,customer_id,age,club_member_status,fashion_news_frequency,last_purchase,purchase_count,total_spent,days_since_last_purchase
5127,00fa6e1d4a247e2c81996af566b8aafd5cf766121d6906...,39,LEFT CLUB,NONE,2020-08-25,2,0.050814,28
5455,0108c5cb6d8a9103de36474ffc70c508fa9c361fc90b05...,53,LEFT CLUB,NONE,2019-04-17,3,0.047407,524
11281,021c897da6d36da705952b4ecc46e641b811e094d67f68...,19,LEFT CLUB,NONE,2019-11-03,6,0.146339,324
11359,02206adfebc3ceec651aee86a3cbb7db83bdbd44aff406...,71,LEFT CLUB,NONE,2019-10-02,24,0.892966,356
14762,02c3a111a4fce8b061a6baad19f1ca5322c3bea8386253...,29,LEFT CLUB,NONE,2019-02-26,17,0.401407,574
...,...,...,...,...,...,...,...,...
1353638,fe5d81720a2ad64193c11617c7cfd069fc61d22f369837...,61,LEFT CLUB,NONE,2020-04-06,5,0.089746,169
1356905,fef8818faad84d92289fec9432ca848e56fb87e76073e9...,25,LEFT CLUB,NONE,2018-10-24,4,0.135525,699
1357441,ff128a0ed5bde04a8105c5d24fd2d141bca7cd1c3490c1...,44,LEFT CLUB,NONE,2019-11-03,46,1.381949,324
1361228,ffcc4dd5f7d2dc78a86729c8d6133debd17671cbbc52a8...,45,LEFT CLUB,NONE,2019-08-06,17,0.581068,413
1361466,ffd7d77fb2d081a05c849bc78a1a1550ff663d7a483bae...,38,LEFT CLUB,Regularly,2019-08-21,4,0.055864,398